# Generated by Django 6.0.6 on 2026-07-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=255)),
                ('subject_title', models.TextField()),
                ('identity', models.FloatField()),
                ('alignment_length', models.IntegerField()),
                ('evalue', models.FloatField()),
                ('bit_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_results', to='proteins.protein')),
            ],
        ),
    ]
