# Generated by Django 6.0.6 on 2026-06-30 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_analysis_exit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=200)),
                ('gene', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=500)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='users.analysis')),
            ],
        ),
    ]
