# Generated by Django 6.0.6 on 2026-06-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_analysis_exit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('waiting', 'Waiting'), ('failed', 'Failed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_modules', to='users.project')),
            ],
        ),
    ]
