# Generated by Django 6.0.6 on 2026-06-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=50)),
                ('probability', models.FloatField()),
                ('cleavage_site', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(default='SignalP', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signalp_result', to='proteins.protein')),
            ],
        ),
    ]
