# Generated by Django 6.0.6 on 2026-07-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_workflowtask'),
        ('proteins', '0001_initial'),
        ('users', '0005_alter_analysis_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanarooRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('genome_count', models.PositiveIntegerField(default=0, help_text='Number of genomes included in this Panaroo run.')),
                ('core_gene_count', models.PositiveIntegerField(default=0)),
                ('accessory_gene_count', models.PositiveIntegerField(default=0)),
                ('output_directory', models.CharField(blank=True, max_length=500)),
                ('log', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panaroo_run', to='pipeline.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='GeneCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(help_text="Panaroo's gene/cluster name, e.g. 'dnaA'.", max_length=300)),
                ('is_core', models.BooleanField(default=False, help_text='True if this gene is present in enough genomes to be considered part of the core genome.')),
                ('genome_count', models.PositiveIntegerField(default=0, help_text='Number of genomes in which this gene was found.')),
                ('panaroo_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_clusters', to='pipeline.panaroorun')),
            ],
            options={
                'ordering': ['-is_core', 'cluster_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pipeline.genecluster')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_cluster_memberships', to='users.genome')),
                ('protein', models.ForeignKey(blank=True, help_text='Null if Panaroo referenced a protein ID that could not be matched back to an imported Protein row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_cluster_memberships', to='proteins.protein')),
            ],
            options={
                'unique_together': {('gene_cluster', 'genome', 'protein')},
            },
        ),
    ]
