# Generated by Django 5.2.15 on 2026-07-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_workflowtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=200)),
                ('locus_tag', models.CharField(blank=True, max_length=200)),
                ('gene', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=500)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='pipeline.workflowrun')),
            ],
            options={
                'ordering': ['protein_id'],
            },
        ),
    ]
