# Generated by Django 6.0.6 on 2026-07-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_panaroorun_genecluster_geneclustermember'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genecluster',
            name='is_essential',
            field=models.BooleanField(default=False, help_text="True if this gene's representative protein had a significant BLAST hit against the Database of Essential Genes (DEG), above the configured identity/e-value/coverage thresholds."),
        ),
        migrations.CreateModel(
            name='DegHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(blank=True, help_text='DEG entry ID of the best hit, if any.', max_length=255)),
                ('identity', models.FloatField(blank=True, null=True)),
                ('alignment_length', models.IntegerField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, help_text='alignment_length / query length, as a percent.', null=True)),
                ('evalue', models.FloatField(blank=True, null=True)),
                ('bit_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gene_cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deg_hit', to='pipeline.genecluster')),
                ('representative_protein', models.ForeignKey(help_text='Which member protein of the gene cluster was used as the query sequence.', on_delete=django.db.models.deletion.CASCADE, related_name='deg_hits', to='proteins.protein')),
            ],
        ),
    ]
