# Generated by Django 6.0.6 on 2026-07-22 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_genecluster_is_essential_deghit'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsortbResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('is_surface_exposed', models.BooleanField(default=False, help_text='True if `localization` is one of settings.PSORTB_SURFACE_LOCALIZATIONS - i.e. this protein is a plausible vaccine target location.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psortb_results', to='proteins.protein')),
            ],
        ),
    ]
