# Generated by Django 6.0.6 on 2026-07-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_psortbresult'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhobiusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_helix_count', models.PositiveIntegerField(default=0)),
                ('has_signal_peptide', models.BooleanField(default=False)),
                ('topology', models.CharField(blank=True, help_text='Raw PREDICTION string from Phobius short output.', max_length=500)),
                ('is_favorable_topology', models.BooleanField(default=False, help_text="True if tm_helix_count <= settings.PHOBIUS_MAX_TM_HELICES - i.e. this protein isn't buried in too many membrane-spanning segments to be a practical vaccine candidate.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phobius_results', to='proteins.protein')),
            ],
        ),
    ]
