# Generated by Django 6.0.6 on 2026-07-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_phobiusresult_prediction_source'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntigenicityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_propensity', models.FloatField(help_text='Whole-protein average Kolaskar-Tongaonkar antigenic propensity score.')),
                ('antigenic_residue_fraction', models.FloatField(help_text="Fraction of scored heptapeptide windows above the method's own per-window cutoff - a finer-grained measure of how much of the protein looks antigenic.")),
                ('is_antigenic', models.BooleanField(default=False, help_text='True if average_propensity >= settings.ANTIGENICITY_THRESHOLD (default 1.0, the cutoff from the original Kolaskar-Tongaonkar paper).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antigenicity_results', to='proteins.protein')),
            ],
        ),
    ]
