# Generated by Django 6.0.6 on 2026-07-23 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_antigenicityresult'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenicityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_subject_id', models.CharField(blank=True, help_text='Allergen database entry ID of the best BLAST hit.', max_length=255)),
                ('identity', models.FloatField(blank=True, null=True)),
                ('alignment_length', models.IntegerField(blank=True, null=True)),
                ('evalue', models.FloatField(blank=True, null=True)),
                ('bit_score', models.FloatField(blank=True, null=True)),
                ('has_sliding_window_hit', models.BooleanField(default=False, help_text='True if identity >= settings.ALLERGEN_MIN_IDENTITY over an alignment >= settings.ALLERGEN_MIN_ALIGNMENT_LENGTH amino acids (the FAO/WHO 35%/80aa criterion).')),
                ('has_exact_match', models.BooleanField(default=False, help_text='True if this protein shares a contiguous settings.ALLERGEN_EXACT_MATCH_LENGTH-mer (default 6) with any sequence in the allergen database (the FAO/WHO exact-match criterion).')),
                ('is_allergen', models.BooleanField(default=False, help_text='True if either has_sliding_window_hit or has_exact_match is True - i.e. this protein is flagged as a potential allergen and is a poor vaccine candidate regardless of its other scores.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergenicity_results', to='proteins.protein')),
            ],
        ),
    ]
