# Generated by Django 6.0.6 on 2026-07-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_allergenicityresult'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_score', models.FloatField(help_text="ToxinPred2's raw ML_Score output (0.0-1.0).")),
                ('is_toxic', models.BooleanField(default=False, help_text="True if ToxinPred2 predicted 'Toxin' (ml_score >= settings.TOXINPRED2_THRESHOLD, default 0.6).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toxicity_results', to='proteins.protein')),
            ],
        ),
    ]
