# Generated by Django 6.0.6 on 2026-07-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_toxicityresult'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCellEpitopeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='Bepipred-2.0', max_length=50)),
                ('total_residues_scored', models.PositiveIntegerField(default=0)),
                ('epitope_residue_count', models.PositiveIntegerField(default=0, help_text="Number of residues Bepipred assigned as part of a predicted linear epitope ('E' assignment).")),
                ('epitope_fraction', models.FloatField(default=0.0)),
                ('has_epitope', models.BooleanField(default=False, help_text='True if epitope_residue_count > 0.')),
                ('raw_result', models.TextField(blank=True, help_text='Raw tab-delimited IEDB API response.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bcell_epitope_result', to='proteins.protein')),
            ],
        ),
        migrations.CreateModel(
            name='MhcIEpitopeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(max_length=50)),
                ('peptide', models.CharField(max_length=50)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('method', models.CharField(default='recommended', max_length=50)),
                ('ic50', models.FloatField(blank=True, null=True)),
                ('percentile_rank', models.FloatField(blank=True, null=True)),
                ('is_strong_binder', models.BooleanField(default=False, help_text='True if percentile_rank <= settings.IEDB_MHCI_PERCENTILE_THRESHOLD (default 2.0, the conventional strong-binder cutoff).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mhci_epitope_results', to='proteins.protein')),
            ],
        ),
        migrations.CreateModel(
            name='MhcIIEpitopeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(max_length=50)),
                ('peptide', models.CharField(max_length=50)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('method', models.CharField(default='recommended', max_length=50)),
                ('ic50', models.FloatField(blank=True, null=True)),
                ('percentile_rank', models.FloatField(blank=True, null=True)),
                ('is_strong_binder', models.BooleanField(default=False, help_text='True if percentile_rank <= settings.IEDB_MHCII_PERCENTILE_THRESHOLD (default 10.0 - MHC-II binding prediction is less precise than MHC-I, so this cutoff is more permissive).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mhcii_epitope_results', to='proteins.protein')),
            ],
        ),
    ]
