# Generated by Django 6.0.6 on 2026-07-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_bcellepitoperesult_mhciepitoperesult_and_more'),
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer_name', models.CharField(default='composite', max_length=50)),
                ('antigenicity_component', models.FloatField(default=0.0)),
                ('localization_component', models.FloatField(default=0.0)),
                ('epitope_component', models.FloatField(default=0.0)),
                ('mhci_coverage_component', models.FloatField(default=0.0)),
                ('mhcii_coverage_component', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(help_text='Weighted sum of the above components, per settings.RANKING_COMPONENT_WEIGHTS. Higher is better.')),
                ('rank', models.PositiveIntegerField(help_text='1-indexed rank within this workflow_run, by final_score descending.')),
                ('explanation', models.TextField(blank=True, help_text='Human-readable breakdown of the score.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rankings', to='proteins.protein')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rankings', to='pipeline.workflowrun')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('workflow_run', 'protein')},
            },
        ),
    ]
