# Generated by Django 6.0.6 on 2026-07-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_candidaterankingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterankingresult',
            name='deg_screened',
            field=models.BooleanField(default=True, help_text="False if the DEG essential-gene screening stage was skipped for this workflow_run (no database configured) - if so, this candidate's essentiality was never confirmed, only assumed as a widened, unscreened pass-through. Always check this before treating a candidate as a validated essential gene."),
        ),
    ]
