# Generated by Django 6.0.6 on 2026-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_candidaterankingresult_deg_screened'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterankingresult',
            name='allergenicity_screened',
            field=models.BooleanField(default=True, help_text='False if the Allergenicity screening stage was skipped for this workflow_run (no allergen database configured) - if so, this candidate has NOT been confirmed non-allergenic, only passed through unscreened.'),
        ),
    ]
