# Generated by Django 6.0.6 on 2026-06-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('annotation', 'Genome Annotation'), ('signalp', 'SignalP'), ('tmhmm', 'TMHMM'), ('psortb', 'PSORTb'), ('blast', 'BLAST'), ('vaxijen', 'VaxiJen'), ('ai', 'AI Analysis')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_directory', models.CharField(blank=True, max_length=500)),
                ('log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.genome')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.project')),
            ],
        ),
    ]
