# Generated by Django 6.0.6 on 2026-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
