# Generated by Django 6.0.6 on 2026-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_analysis_exit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('bakta', 'Bakta Annotation'), ('panaroo', 'Panaroo Pan-Genome'), ('deg_filter', 'Essential Gene Filter (DEG)'), ('human_homology', 'Human Homology (DIAMOND/BLAST)'), ('psortb', 'PSORTb Localization'), ('phobius', 'Phobius'), ('antigenicity', 'Antigenicity'), ('allergenicity', 'Allergenicity'), ('toxicity', 'Toxicity'), ('iedb', 'IEDB Epitope Prediction'), ('ai_ranking', 'AI Candidate Ranking')], max_length=50),
        ),
    ]
