# Generated by Django 6.0.6 on 2026-07-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_analysis_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gram_stain',
            field=models.CharField(choices=[('negative', 'Gram Negative'), ('positive', 'Gram Positive'), ('archaea', 'Archaea')], default='negative', help_text='Determines which PSORTb analysis mode is used for subcellular localization prediction. Defaults to Gram Negative - check this is correct for your organism before running the PSORTb stage.', max_length=20),
        ),
    ]
