"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# -----------------------------------------------------------------------------
# Base Directory
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------------------------------------------------------
# Security
# -----------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-(5jo1a(bz7whv^ed0u(^ttcil40unck0b0rg7!1r1&7$k31^p^",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h
]


# -----------------------------------------------------------------------------
# Bakta (pipeline external tool paths — machine-specific, keep out of source)
# -----------------------------------------------------------------------------

BAKTA_EXECUTABLE = os.environ.get(
    "BAKTA_EXECUTABLE",
    "/home/rahul/miniconda3/envs/vaxiflow/bin/bakta",
)

BAKTA_DB = os.environ.get(
    "BAKTA_DB",
    "/mnt/d/VaxiFlowData/bakta-light/db-light",
)

PANAROO_EXECUTABLE = os.environ.get(
    "PANAROO_EXECUTABLE",
    "/home/rahul/miniconda3/envs/vaxiflow/bin/panaroo",
)

PANAROO_MIN_GENOMES = int(
    os.environ.get("PANAROO_MIN_GENOMES", "2")
)

# Essential Gene Filter (DEG) - BLASTP against the Database of
# Essential Genes. Thresholds follow the commonly used DEG
# homology-based essentiality convention (see DEG documentation).
DEG_BLASTP_EXECUTABLE = os.environ.get(
    "DEG_BLASTP_EXECUTABLE",
    "blastp",
)

DEG_DATABASE = os.environ.get(
    "DEG_DATABASE",
    "/mnt/d/VaxiFlowData/deg-db/deg",
)

DEG_MIN_IDENTITY = float(
    os.environ.get("DEG_MIN_IDENTITY", "30.0")
)

DEG_MAX_EVALUE = float(
    os.environ.get("DEG_MAX_EVALUE", "1e-10")
)

DEG_MIN_COVERAGE = float(
    os.environ.get("DEG_MIN_COVERAGE", "70.0")
)

HUMAN_HOMOLOGY_MAX_IDENTITY = float(
    os.environ.get("HUMAN_HOMOLOGY_MAX_IDENTITY", "30.0")
)

# PSORTb - bacterial subcellular localization prediction.
PSORTB_EXECUTABLE = os.environ.get(
    "PSORTB_EXECUTABLE",
    "psort",
)

# Localizations considered viable vaccine targets (surface-exposed
# or secreted, i.e. reachable by antibodies).
PSORTB_SURFACE_LOCALIZATIONS = [
    "OuterMembrane",
    "Extracellular",
]

# Phobius - signal peptide + transmembrane topology prediction.
# Proteins with more transmembrane helices than this are considered
# poor vaccine candidates (hard to express recombinantly, mostly
# buried rather than surface-accessible).
PHOBIUS_EXECUTABLE = os.environ.get(
    "PHOBIUS_EXECUTABLE",
    "/opt/phobius/phobius.pl",
)

PHOBIUS_MAX_TM_HELICES = int(
    os.environ.get("PHOBIUS_MAX_TM_HELICES", "1")
)

# Antigenicity (Kolaskar & Tongaonkar, 1990) - the canonical cutoff
# from the original paper; average propensity >= this is considered
# a probable antigenic determinant.
ANTIGENICITY_THRESHOLD = float(
    os.environ.get("ANTIGENICITY_THRESHOLD", "1.0")
)

# Allergenicity - homology-based screening against a curated allergen
# database (e.g. AllergenOnline), per the FAO/WHO (2001) guidelines:
# a protein is flagged as a potential allergen if it has >=35%
# identity to a known allergen over an alignment of at least 80
# amino acids, OR an exact match of 6+ contiguous amino acids.
ALLERGEN_BLASTP_EXECUTABLE = os.environ.get(
    "ALLERGEN_BLASTP_EXECUTABLE",
    "blastp",
)

ALLERGEN_DATABASE = os.environ.get(
    "ALLERGEN_DATABASE",
    "/mnt/d/VaxiFlowData/allergen-db/allergenonline",
)

ALLERGEN_DATABASE_FASTA = os.environ.get(
    "ALLERGEN_DATABASE_FASTA",
    "/mnt/d/VaxiFlowData/allergen-db/allergenonline.fasta",
)

ALLERGEN_MIN_IDENTITY = float(
    os.environ.get("ALLERGEN_MIN_IDENTITY", "35.0")
)

ALLERGEN_MIN_ALIGNMENT_LENGTH = int(
    os.environ.get("ALLERGEN_MIN_ALIGNMENT_LENGTH", "80")
)

ALLERGEN_EXACT_MATCH_LENGTH = int(
    os.environ.get("ALLERGEN_EXACT_MATCH_LENGTH", "6")
)

# Toxicity - ToxinPred2 (Raghava lab), installed via pip. Unlike
# VaxiJen/AllerTOP/Phobius, this is a genuinely installable,
# verified-working tool - no fallback needed.
TOXINPRED2_EXECUTABLE = os.environ.get(
    "TOXINPRED2_EXECUTABLE",
    "toxinpred2",
)

# 1: AAC-based Random Forest (fast), 2: Hybrid (slower, more
# accurate). Matches the tool's own -m flag.
TOXINPRED2_MODEL = os.environ.get("TOXINPRED2_MODEL", "1")

TOXINPRED2_THRESHOLD = os.environ.get(
    "TOXINPRED2_THRESHOLD", "0.6"
)

# IEDB Epitope Prediction - calls the real IEDB Tools API
# (tools-cluster-interface.iedb.org) at runtime rather than bundling
# a local database, matching the "offload via remote API" design.
IEDB_API_BASE_URL = os.environ.get(
    "IEDB_API_BASE_URL",
    "https://tools-cluster-interface.iedb.org/tools_api",
)

IEDB_REQUEST_TIMEOUT = int(
    os.environ.get("IEDB_REQUEST_TIMEOUT", "180")
)

# B-cell (linear/continuous epitope prediction).
IEDB_BCELL_METHOD = os.environ.get(
    "IEDB_BCELL_METHOD", "Bepipred-2.0"
)

# MHC class I binding - default panel chosen for broad global HLA-A/B
# population coverage, a commonly used reference set in reverse
# vaccinology screening. Override via env (comma-separated) for a
# population-specific panel.
IEDB_MHCI_ALLELES = os.environ.get(
    "IEDB_MHCI_ALLELES",
    "HLA-A*02:01,HLA-A*01:01,HLA-A*03:01,HLA-A*24:02,"
    "HLA-B*07:02,HLA-B*08:01",
).split(",")

IEDB_MHCI_PEPTIDE_LENGTHS = [
    int(x)
    for x in os.environ.get(
        "IEDB_MHCI_PEPTIDE_LENGTHS", "9"
    ).split(",")
]

IEDB_MHCI_METHOD = os.environ.get(
    "IEDB_MHCI_METHOD", "recommended"
)

# Conventional strong-binder cutoff for MHC-I percentile rank.
IEDB_MHCI_PERCENTILE_THRESHOLD = float(
    os.environ.get("IEDB_MHCI_PERCENTILE_THRESHOLD", "2.0")
)

# MHC class II binding - default DRB1 reference panel, commonly used
# for broad population coverage in epitope screening.
IEDB_MHCII_ALLELES = os.environ.get(
    "IEDB_MHCII_ALLELES",
    "HLA-DRB1*01:01,HLA-DRB1*03:01,HLA-DRB1*04:01,"
    "HLA-DRB1*07:01,HLA-DRB1*15:01",
).split(",")

IEDB_MHCII_METHOD = os.environ.get(
    "IEDB_MHCII_METHOD", "recommended"
)

# MHC-II binding prediction is less precise than MHC-I, so the
# conventional strong-binder percentile cutoff is more permissive.
IEDB_MHCII_PERCENTILE_THRESHOLD = float(
    os.environ.get("IEDB_MHCII_PERCENTILE_THRESHOLD", "10.0")
)

# AI Candidate Ranking - a transparent, explainable composite scoring
# function, NOT a trained ML model (there is no labeled dataset of
# validated vaccine candidates to train one honestly). Architected
# with a named `RANKING_SCORER` seam so a genuine trained model can
# be swapped in later (see pipeline.services.tools.candidate_scorer)
# without redesigning the pipeline.
RANKING_SCORER = os.environ.get("RANKING_SCORER", "composite")

# Equal weighting by default - this is a documented heuristic
# default, not a value tuned against real outcomes (no labeled data
# exists to tune against). Override via env as a comma-separated
# "component:weight" list if you have expert-informed weights.
RANKING_COMPONENT_WEIGHTS = {
    "antigenicity": 0.2,
    "localization": 0.2,
    "epitope": 0.2,
    "mhci_coverage": 0.2,
    "mhcii_coverage": 0.2,
}

_ranking_weights_override = os.environ.get(
    "RANKING_COMPONENT_WEIGHTS", ""
)

if _ranking_weights_override:

    RANKING_COMPONENT_WEIGHTS = {}

    for _pair in _ranking_weights_override.split(","):
        _key, _value = _pair.split(":")
        RANKING_COMPONENT_WEIGHTS[_key.strip()] = float(_value)

# Plausible min/max whole-protein Kolaskar-Tongaonkar average
# propensity, used to normalize that score into a 0-1 range for
# the composite ranking (residue-level scale extremes are ~0.776 to
# ~1.412; whole-protein averages cluster more centrally, so a
# narrower 0.8-1.3 window is used).
RANKING_ANTIGENICITY_MIN = float(
    os.environ.get("RANKING_ANTIGENICITY_MIN", "0.8")
)

RANKING_ANTIGENICITY_MAX = float(
    os.environ.get("RANKING_ANTIGENICITY_MAX", "1.3")
)


# -----------------------------------------------------------------------------
# Installed Applications
# -----------------------------------------------------------------------------

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # VaxiFlow Apps
    'users',
    'proteins',
    'signalp',
    'analysis_center',

    'blast',
    'django_extensions',
    'pipeline',
    
    


    

]


# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -----------------------------------------------------------------------------
# URLs
# -----------------------------------------------------------------------------

ROOT_URLCONF = 'config.urls'


# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -----------------------------------------------------------------------------
# WSGI
# -----------------------------------------------------------------------------

WSGI_APPLICATION = 'config.wsgi.application'


# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -----------------------------------------------------------------------------
# Password Validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -----------------------------------------------------------------------------
# Static Files
# -----------------------------------------------------------------------------

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# -----------------------------------------------------------------------------
# Media Files
# -----------------------------------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# ==========================================
# BLAST Configuration
# ==========================================

BLAST_DATABASES = {

    "human_swissprot": BASE_DIR
    / "blast_data"
    / "human"
    / "swissprot"
    / "human_proteome",

}

BLAST_OUTPUT_DIRECTORY = BASE_DIR / "media" / "blast"


# -----------------------------------------------------------------------------
# Default Primary Key
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

