"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# -----------------------------------------------------------------------------
# Base Directory
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------------------------------------------------------
# Security
# -----------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-(5jo1a(bz7whv^ed0u(^ttcil40unck0b0rg7!1r1&7$k31^p^",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h
]


# -----------------------------------------------------------------------------
# Bakta (pipeline external tool paths — machine-specific, keep out of source)
# -----------------------------------------------------------------------------

BAKTA_EXECUTABLE = os.environ.get(
    "BAKTA_EXECUTABLE",
    "/home/rahul/miniconda3/envs/vaxiflow/bin/bakta",
)

BAKTA_DB = os.environ.get(
    "BAKTA_DB",
    "/mnt/d/VaxiFlowData/bakta-light/db-light",
)

PANAROO_EXECUTABLE = os.environ.get(
    "PANAROO_EXECUTABLE",
    "/home/rahul/miniconda3/envs/vaxiflow/bin/panaroo",
)

PANAROO_MIN_GENOMES = int(
    os.environ.get("PANAROO_MIN_GENOMES", "2")
)

# Essential Gene Filter (DEG) - BLASTP against the Database of
# Essential Genes. Thresholds follow the commonly used DEG
# homology-based essentiality convention (see DEG documentation).
DEG_BLASTP_EXECUTABLE = os.environ.get(
    "DEG_BLASTP_EXECUTABLE",
    "blastp",
)

DEG_DATABASE = os.environ.get(
    "DEG_DATABASE",
    "/mnt/d/VaxiFlowData/deg-db/deg",
)

DEG_MIN_IDENTITY = float(
    os.environ.get("DEG_MIN_IDENTITY", "30.0")
)

DEG_MAX_EVALUE = float(
    os.environ.get("DEG_MAX_EVALUE", "1e-10")
)

DEG_MIN_COVERAGE = float(
    os.environ.get("DEG_MIN_COVERAGE", "70.0")
)

HUMAN_HOMOLOGY_MAX_IDENTITY = float(
    os.environ.get("HUMAN_HOMOLOGY_MAX_IDENTITY", "30.0")
)

# PSORTb - bacterial subcellular localization prediction.
PSORTB_EXECUTABLE = os.environ.get(
    "PSORTB_EXECUTABLE",
    "psort",
)

# Localizations considered viable vaccine targets (surface-exposed
# or secreted, i.e. reachable by antibodies).
PSORTB_SURFACE_LOCALIZATIONS = [
    "OuterMembrane",
    "Extracellular",
]

# Phobius - signal peptide + transmembrane topology prediction.
# Proteins with more transmembrane helices than this are considered
# poor vaccine candidates (hard to express recombinantly, mostly
# buried rather than surface-accessible).
PHOBIUS_EXECUTABLE = os.environ.get(
    "PHOBIUS_EXECUTABLE",
    "/opt/phobius/phobius.pl",
)

PHOBIUS_MAX_TM_HELICES = int(
    os.environ.get("PHOBIUS_MAX_TM_HELICES", "1")
)

# Antigenicity (Kolaskar & Tongaonkar, 1990) - the canonical cutoff
# from the original paper; average propensity >= this is considered
# a probable antigenic determinant.
ANTIGENICITY_THRESHOLD = float(
    os.environ.get("ANTIGENICITY_THRESHOLD", "1.0")
)

# Allergenicity - homology-based screening against a curated allergen
# database (e.g. AllergenOnline), per the FAO/WHO (2001) guidelines:
# a protein is flagged as a potential allergen if it has >=35%
# identity to a known allergen over an alignment of at least 80
# amino acids, OR an exact match of 6+ contiguous amino acids.
ALLERGEN_BLASTP_EXECUTABLE = os.environ.get(
    "ALLERGEN_BLASTP_EXECUTABLE",
    "blastp",
)

ALLERGEN_DATABASE = os.environ.get(
    "ALLERGEN_DATABASE",
    "/mnt/d/VaxiFlowData/allergen-db/allergenonline",
)

ALLERGEN_DATABASE_FASTA = os.environ.get(
    "ALLERGEN_DATABASE_FASTA",
    "/mnt/d/VaxiFlowData/allergen-db/allergenonline.fasta",
)

ALLERGEN_MIN_IDENTITY = float(
    os.environ.get("ALLERGEN_MIN_IDENTITY", "35.0")
)

ALLERGEN_MIN_ALIGNMENT_LENGTH = int(
    os.environ.get("ALLERGEN_MIN_ALIGNMENT_LENGTH", "80")
)

ALLERGEN_EXACT_MATCH_LENGTH = int(
    os.environ.get("ALLERGEN_EXACT_MATCH_LENGTH", "6")
)

# Toxicity - ToxinPred2 (Raghava lab), installed via pip. Unlike
# VaxiJen/AllerTOP/Phobius, this is a genuinely installable,
# verified-working tool - no fallback needed.
TOXINPRED2_EXECUTABLE = os.environ.get(
    "TOXINPRED2_EXECUTABLE",
    "toxinpred2",
)

# 1: AAC-based Random Forest (fast), 2: Hybrid (slower, more
# accurate). Matches the tool's own -m flag.
TOXINPRED2_MODEL = os.environ.get("TOXINPRED2_MODEL", "1")

TOXINPRED2_THRESHOLD = os.environ.get(
    "TOXINPRED2_THRESHOLD", "0.6"
)


# -----------------------------------------------------------------------------
# Installed Applications
# -----------------------------------------------------------------------------

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # VaxiFlow Apps
    'users',
    'proteins',
    'signalp',
    'analysis_center',

    'blast',
    'django_extensions',
    'pipeline',
    
    


    

]


# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -----------------------------------------------------------------------------
# URLs
# -----------------------------------------------------------------------------

ROOT_URLCONF = 'config.urls'


# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# -----------------------------------------------------------------------------
# WSGI
# -----------------------------------------------------------------------------

WSGI_APPLICATION = 'config.wsgi.application'


# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -----------------------------------------------------------------------------
# Password Validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -----------------------------------------------------------------------------
# Static Files
# -----------------------------------------------------------------------------

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# -----------------------------------------------------------------------------
# Media Files
# -----------------------------------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# ==========================================
# BLAST Configuration
# ==========================================

BLAST_DATABASES = {

    "human_swissprot": BASE_DIR
    / "blast_data"
    / "human"
    / "swissprot"
    / "human_proteome",

}

BLAST_OUTPUT_DIRECTORY = BASE_DIR / "media" / "blast"


# -----------------------------------------------------------------------------
# Default Primary Key
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

